name: CI
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.2'
            activerecord: '~> 7.2.0'
          - ruby: '3.4'
            activerecord: '~> 8.0.0'
          - ruby: '3.4'
            activerecord: '~> 8.1.0'

    name: Ruby ${{ matrix.ruby }} / AR ${{ matrix.activerecord }}
    env:
      ACTIVERECORD_VERSION: ${{ matrix.activerecord }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Tests
        run: bundle exec rspec

      - name: Rubocop
        run: bundle exec rubocop
